### ISSUE TITLE
Error in macvim

### ISSUE THREAD

**Issue by akulakov** [AndrewRadev/sideways.vim#12]
In macvim, when trying the basic sideways command, I get:

Error detected while processing function sideways#MoveRight..sideways#Parse:
line    7:
E117: Unknown function: sideways#parsing#Parse
E15: Invalid expression: sideways#parsing#Parse(definitions)

**Comment by AndrewRadev** [comment]
I'm not sure how to debug this. It seems like there's some problem with your installation, but I don't know what. Did you install it using pathogen or some other plugin manager? In that case, could you check if you have an `~/.vim/bundle/sideways/autoload/` directory (or something along those lines)?

Or, if you've just copied the files in your `~/.vim` directory, you should have a `~/.vim/autoload/sideways/` directory.

**Comment by AndrewRadev** [comment]
I can't say what the issue was here, but it's been a while, so I'll go ahead and close it.
