### ISSUE TITLE
Doesn't seem to detect last argument

### ISSUE THREAD

**Issue by spinningarrow** [AndrewRadev/sideways.vim#17]
I'm seeing an issue where sideways doesn't recognise the last argument/item. For example if I have this code:

    [ 1, 2, 3 ]

and I put my cursor on `1` and execute `:SidewaysRight`, I get

    [ 2, 1, 3 ]

as expected. But if I put my cursor back on `1` and execute `:SidewaysRight` again, I get

    [ 1, 2, 3 ]

but it should be `[ 2, 3, 1 ]`, shouldn't it? Am I doing something wrong?

Tested with both JS and Ruby files.

**Comment by AndrewRadev** [comment]
You're right, it's definitely a bug, it's happening for one-symbol items, and I think I recently manage to introduce it. Thanks for reporting it!

I've pushed a fix to master, could you check it out and let me know if it works for you now?

**Comment by spinningarrow** [comment]
Yup, it looks like it's fixed now. Cheers, and thanks for the useful plugin!
