### ISSUE TITLE
Doesn't work when the delimiter starts on a new line

### ISSUE THREAD

**Issue by adriaanzon** [AndrewRadev/sideways.vim#18]
I'm trying to make this plugin work on chained methods in PHP, with the following configuration:

```vim
autocmd FileType php let b:sideways_definitions = [{
      \   'start': '\(\w\+::\|\$\w\+->\)\_s*',
      \   'end': ';',
      \   'delimiter': '\_s*->\_s*',
      \   'brackets':  ['(', ')'],
      \ }]
```

On a single line it works fine. It also works when the delimiter is at the end of a line, like this:

```php
Route::get('/')->
    as('home')->
    middleware('web');
```

But when the delimiter starts on a new  line (like you normally would with method chaining), it does not  work.

```php
Route::get('/')
    ->as('home')
    ->middleware('web');
```

As an example, it also doesn't work when you try it out on regular functions:

```
foo(bar
   ,baz
   ,fizz)
```

It looks like it has to do something with [this part here](https://github.com/AndrewRadev/sideways.vim/blob/master/autoload/sideways/parsing.vim#L83-L85), but I can't really figure out a way to make it work.

**Comment by AndrewRadev** [comment]
I'd like to start by saying I *really* dislike this style of putting operators on the next line. With a `->` on the next line, the current line is perfectly complete. Any parser, interpreter, or argument-parsing Vim plugin now has to check the next line in case it happens to modify the meaning of the current one.

That said, it's a valid thing that people do, I suppose. And in this case, I think I managed to hack around the issue by checking the next line for the delimiter. I'm not 100% sure it won't cause issues, but the test suite is passing, so I've pushed the change to master. Could you try it out and see if it works for your use cases?

**Comment by adriaanzon** [comment]
That works perfectly fine. Thank you!
