### ISSUE TITLE
Wrong text object for an argument at the beginning of a line

### ISSUE THREAD

**Issue by boris-petrov** [AndrewRadev/sideways.vim#22]
```
function(a, b,
c, d)
```

When the cursor is on `c` and `daa` is used, the result is this:

```
function(a, b,
, d)
```

Which is, obviously, not correct.

**Comment by idbrii** [comment]
You'd expect this:

    function(a, b,
    d)

I think this is more a failure to find the preceding comma than using the I object instead of the A object.

Similarly, with the cursor on the comma after `b`, and daa, you get:

    function)

(on 2d5cd2b3cb853067f192cd0e445c35e6007d6fe3)

Sidenote: I recently upgraded from abc255142b5a96d1ea7bfbe48839e5e94887bd8c which had slightly different but not better/worse behavior:

    function, d)

**Comment by AndrewRadev** [comment]
So, I think I managed to fix the problem. In general, the plugin tries to select the argument with the *preceding* comma, which causes the problem. In this particular case, the correct thing to do would be to select it with the *next* one. 

(The commit that fixes it is here: https://github.com/AndrewRadev/sideways.vim/commit/01a96f716bad0f7b03043a779e49550139fa2069. This is more of a reference for @boris-petrov who has a desire to know how the plugin is implemented)

Could you try it out now and let me know if it works correctly, @boris-petrov, @idbrii?

**Comment by boris-petrov** [comment]
@AndrewRadev - thanks for the support! It seems to work in some cases, but in others it breaks:

```
test(object,
  someText)
```

When the cursor is on `someText` and `daa` is pressed - the result is `test(o)`.

Also, another thing I noticed is that it doesn't work in more complex cases (if that's too complicated - it is with a really low priority - the problem above is way more important):

```
x(a,
  b(
  ), c);
```

When on `b`, pressing `daa` breaks pretty much everything.

**Comment by AndrewRadev** [comment]
> When the cursor is on someText and daa is pressed - the result is test(o).

Whoops, shouldn't have tested with one-character variables. Should be fixed.

**Comment by AndrewRadev** [comment]
> Also, another thing I noticed is that it doesn't work in more complex cases

The problem in the second case is that the argument itself is split over more than one line, and the structure the plugin uses to mark arguments just doesn't support this -- arguments are marked with a `[line number, start col, end col]`. Splitting the line number into a start and end would be a start, but afterwards, I'd need to go around and figure out the logic. Not saying it can't be done, but I'd argue it's a separate issue that should be opened after this one is closed, that will probably wait for a while until I get around to it.

**Comment by boris-petrov** [comment]
OK, thanks a bunch, seems to work fine now! Thank you for the support! I'll open a new issue of the other example.

**Comment by boris-petrov** [comment]
@AndrewRadev - I found another case when this breaks. Perhaps the issue should be reopened.

```
a(
    b()
        .a(),
    "qwe"));
```

When on `qwe`, `daa` doesn't do the right thing. Not sure if this is the same as the other issue that I opened.

**Comment by AndrewRadev** [comment]
It's the same problem as #25. A single argument can't span more than one line, and `b().a()` is a single argument.
