### ISSUE TITLE
Wrong text object for an argument with parentheses on multiple lines

### ISSUE THREAD

**Issue by boris-petrov** [AndrewRadev/sideways.vim#25]
Having:

```
x(a,
  b(
  ), c);
```

When the cursor is on `b` and `daa` is pressed, the result is `x);`.

**Comment by AndrewRadev** [comment]
I think I managed to fix the issue -- it works for this particular example, at least. I did have to touch quite a few internals in the process, so I've made it in a branch: `single-arguments-on-multiple-lines`. Try using it for a while, and report if you get any errors or strange behaviour. If it seems to work well in a week or two of normal usage, I'll merge it in. Sound good?

**Comment by boris-petrov** [comment]
Will do, thanks!

**Comment by AndrewRadev** [comment]
This should be fixed now in master, I've merged the branch. Closing, reopen if the issue reoccurs.
