### ISSUE TITLE
Wrong text object for an argument before a brace

### ISSUE THREAD

**Issue by boris-petrov** [AndrewRadev/sideways.vim#27]
Not sure the title is correct. The example is (JavaScript):

```javascript
new Foo('bar', {
    ...
```

When the cursor is on `'bar'` and `daa` is pressed, the result is:

```javascript
new Foo(, {
```

**Comment by AndrewRadev** [comment]
The source of this problem is the same one as #22, but it's a different issue, so fair enough. It should be fixed on the branch `single-arguments-on-multiple-lines`, so, like I said in #22, try it out for a while, and I'll merge it to master if it's stable.

**Comment by AndrewRadev** [comment]
I've merged the branch, so I'll go ahead and close this issue. Reopen if it turns out there's some related bug.
