### ISSUE TITLE
Wrong text object for [:] as an argument

### ISSUE THREAD

**Issue by boris-petrov** [AndrewRadev/sideways.vim#28]
I noticed this before, doesn't work correctly even with the new branch:

```groovy
foo(123, [:], 456);
```

When on `[:]`, pressing `daa` leads to `foo(123, [], 456)`.

**Comment by AndrewRadev** [comment]
Which language is this? For ruby, this works fine for me, but it matters where the cursor is. If the cursor is on the `[`, the entire `[:]` gets deleted. Otherwise, the `[ ]` is considered a nested list, so `:` is its first (and only) argument.

**Comment by boris-petrov** [comment]
hm, you're obviously right. That was an example in Groovy. But yes, of course, when *inside* the brackets, that should be the result. Sorry for the confusion.

**Comment by boris-petrov** [comment]
Ok, I'm reopening so I don't open too many issues. :) When there is an empty-list argument (`[]`) and the cursor is on the **closing** brace, `daa` does nothing. On the opening in correctly removes the list.

**Comment by AndrewRadev** [comment]
I think I managed to fix it, in the `single-arguments-on-multiple-lines` branch (was going to be tricky to merge if I made it in master, and it's enough of an edge case I can afford to wait until I've merged the branch).

**Comment by AndrewRadev** [comment]
I've merged the branch, and it seems to be working well now. I'll close this issue, but feel free to reopen if it turns out there's a related problem.
