### ISSUE TITLE
More targets than List items

### ISSUE THREAD

**Issue by bstaint** [AndrewRadev/sideways.vim#29]
when sideways#parsing#Parse return []:
```
Error detected while processing function sideways#MoveLeft:
line    1:
E688: More targets than List items
line    2:
E121: Undefined variable: items
E116: Invalid arguments for function empty(items)
E15: Invalid expression: empty(items)
...
```

sideways.vim\autoload\sideways\parsing.vim, line 38:
```
    return [definition []]
```
instead.

**Comment by AndrewRadev** [comment]
Good catch, thank you very much for the backtrace and the suggestion -- I've pushed a fix. Could you pull from master and confirm it works right?

**Comment by bstaint** [comment]
Yes, It's no problem. thx.
