### ISSUE TITLE
Support for python import

### ISSUE THREAD

**Issue by hulucc** [AndrewRadev/sideways.vim#33]
Exchange `Class1` with `Class2`
```
from package.module import Class1, Class2
```

**Comment by AndrewRadev** [comment]
I've implemented the functionality in master. Could you pull and test it out? I don't write a lot of python, so I don't know if I've tested all the edge cases -- let me know if you find any issues.

**Comment by hulucc** [comment]
It turn out is something wrong with lazy load of plugin manager. It works now, thank u.
