### ISSUE TITLE
Wrong text object for an argument - (A<B, D> asd)

### ISSUE THREAD

**Issue by boris-petrov** [AndrewRadev/sideways.vim#35]
This doesn't work right:

`(A<B, D> asd)`

Be on `A` and press `daa` - the result is `(D> asd)`.

**Comment by AndrewRadev** [comment]
This seems to be working now as expected -- `daa` on the `A` should delete the whole argument. The fix is probably due to some changes I've made to get Rust support to work right, but not 100% sure if it'll work reliably.

**Comment by boris-petrov** [comment]
It doesn't seem to work for Java. For example:

```java
public Foo(Map<String, Object> map) {
```

Being on `M` and pressing `daa` - this is left: `public Foo(Object> map) {`.

It seems to work for a single type argument though.

**Comment by AndrewRadev** [comment]
I had only tested it for C++. I just added support for Java that should work the same way.

**Comment by boris-petrov** [comment]
Yes, this is now fixed, thanks for the support!
