### ISSUE TITLE
Comma at beginning of line causes wrong text selection

### ISSUE THREAD

**Issue by lrworth** [AndrewRadev/sideways.vim#38]
```
( ab
, cd
, ef
)
```
Place cursor on `cd` or `ef` and enter `vaa` - it also selects the last character of the previous line.

**Comment by AndrewRadev** [comment]
That's a good catch. The source seems to be difficulties with selecting the right area in that situation. I've pushed a commit to master that should fix the issue -- could you try it out and let me know if it works for you now?

**Comment by lrworth** [comment]
Beautiful! Thankyou for your work @AndrewRadev!
