### ISSUE TITLE
How to add custom definitions without forking this plugin?

### ISSUE THREAD

**Issue by Arnie97** [AndrewRadev/sideways.vim#49]
HI, thanks for the awesome plugin.

I'm trying to add a new custom rule to swap the case options in go's switch-case statements:

```go
case foo, bar, baz:
```

So I put these in my vimrc, but with no luck:
```vim
call plug#begin('~/.vim/plug')
    Plug 'AndrewRadev/sideways.vim'
call plug#end()

autocmd! FileType go let b:sideways_definitions = [
    \ {
    \     'start':     'case ',
    \     'end':       ':',
    \     'delimiter': ',\s*',
    \     'brackets':  ['([''"', ')]''"'],
    \ },
\ ]
```

I know there're sane defaults defined in [`sideways.vim/plugin/sideways.vim`](https://github.com/AndrewRadev/sideways.vim/blob/main/plugin/sideways.vim), and they seem to override my custom setup, as the plugin code in `&runtimepath` is loaded after `.vimrc`:
```vim
:autocmd FileType go
--- Autocommands ---
FileType
    go        let b:sideways_definitions = [   {     'start':     'case ',     'end':       ':',     'delimiter': ',\s*',     'brackets':  ['([''"', ')]''"'], }, ]
    go        let b:sideways_definitions = [   {     'start':     '{\_s*',     'end':       '\_s*}',     'delimiter': ',\s*',   'brackets':  ['([''"', ')]''"'],   }, ]
Press ENTER or type command to continue

:echo b:sideways_definitions
[{'end': '\_s*}', 'brackets': ['([''"', ')]''"'], 'start': '{\_s*', 'delimiter': ',\s*'}]
```

Now I've create a "plugin" with my sideways definitions, and put it at the end of my `&rtp`. But I guess the customization process could be made easier, so I'm looking for idea and suggestions. Thanks.

Edit: the custom `g:sideways_definitions` in vimrc is also overridden by the defaults, so I've changed the title.

**Comment by elchiquics** [comment]
I have one solution:
First you defined by `autocmd` your extra definitions in your `.vimrc` , I chose this way:
``` vim
autocmd FileType go let b:extra_defs = [
      \ {
        \     'start':     'case\s*',
        \     'end':       '\s*:',
        \     'delimiter': '\s*,\s*',
        \     'brackets':  ['([''"', ')]''"'],
        \ },
        \ ]
```
Second step , use `autocmd` to add your custom definitions after you enter to a Go file:

``` vim
autocmd BufWinEnter *.go execute 'let b:sideways_definitions += b:extra_defs'
```

**Comment by AndrewRadev** [comment]
The solution suggested by @elchiquics could work, but I do think it makes more sense to make it easier within the plugin.

What I've done in the branch [customize-definitions](https://github.com/AndrewRadev/sideways.vim/tree/customize-definitions) is:

- I've moved all the autocommands to their dedicated ftplugin files.
- I've added a check whether the `b:sideways_definitions` variable is already set

This means that, however you end up creating `b:sideways_definitions`, the plugin should now end up using your version of that variable. Could you try that out?

Additionally, you can *extend* the definitions by using `b:sideways_custom_definitions`. I'd appreciate if you try that as well.

If it all seems to work well, I'll sit down to write some documentation and merge the branch.

**Comment by Arnie97** [comment]
I've tested both `b:sideways_definitions` and `b:sideways_custom_definitions`, and they worked like a charm.

For consistency with buffer specific vars, I'd suggest to handle `g:sideways_definitions` and `g:sideways_custom_definitions` in the same way. Thanks you.

**Comment by AndrewRadev** [comment]
I've added support for the global variables, and I've written some explanations in `:help sideways-customize`. I figure there's no need to keep it in a branch anymore, so I've merged it, and I'll consider this issue closed for now. Feel free to reopen if you run into any problems.
