### ISSUE TITLE
Does not work correctly in typescript

### ISSUE THREAD

**Issue by mphe** [AndrewRadev/sideways.vim#54]
Shifting does not work correctly in typescript when types are specified.

This works fine:
```typescript
function foo(a, b, c) {
    console.log(a, b)
}
```

This doesn't:
```typescript
function foo(a: number, b: number, c: number) {
    console.log(a, b)
}
```

Using `:SidewaysRight` or `:SidewaysLeft` on the first argument 'a' works as expected.
Using `:SidewaysRight` or `:SidewaysLeft` on any other argument, does not shift anything, but always places the cursor to the next type definition to the left.

E.g.:
Cursor is on 'b' + `:SidewaysRight` => Nothing is shifted, cursor shifts to 'number' after 'a'.

**Comment by AndrewRadev** [comment]
Hmm, it was getting confused with `interface Foo { value: A | B | C }`. I've added some logic to make that case more specific. Seems like your example works for me now -- could you try it out as well?

**Comment by mphe** [comment]
That seems to work.
Thanks for the quick fix and the great plugin!
